### ISSUE TITLE
Yeah, yeah, yeah, go, go away Yeah, yeah, yeah, yeah, yeah Yeah, yeah, yeah, go, go away Yeah, yeah, yeah, yeah, yeah Yeah, yeah, yeah, go, go away Yeah, yeah, yeah, yeah, yeah Yeah, yeah, yeah, go, go away

### ISSUE THREAD

**Issue by ranon-rat** [FlamesX-128/FlamesX-128#1]
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, go, go away
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, go, go away
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, go, go away
Yeah, yeah, yeah, yeah, yeah
Yeah, yeah, yeah, go, go away
We just wanna party
Party just for you
We just want the money
Money just for you
I know you wanna party (yeah)
Party just for free
Girl, you got me dancin' (girl, you got me dancin')
Dance and shake the frame
We just wanna party (yeah)
Party just for you (yeah)
We just want the money (yeah)
Money just for you (ooh)
I know you wanna party (yeah)
Party just for free (yeah)
Girl, you got me dancin' (girl, you got me dancin')
Dance and shake the frame (ooh)
This is America
Don't catch you slippin' now
Don't catch you slippin' now
Look what I'm whippin' now
This is America (woo)
Don't catch you slippin' now
Don't catch you slippin' now
Look what I'm whippin' now
This is America (skrrt, skrrt, woo)
Don't catch you slippin' now (ayy)
Look at how I'm livin' now
Police be trippin' now (woo)
Yeah, this is America (woo, ayy)
Guns in my area (word, my area)
I got the strap (ayy, ayy)
I gotta carry 'em
Yeah, yeah, I'ma go into this (ugh)
Yeah, yeah, this is guerilla, woo
Yeah, yeah, I'ma go get the bag
Yeah, yeah, or I'ma get the pad
Yeah, yeah, I'm so cold like yeah (yeah)
I'm so dope like yeah (woo)
We gon' blow like yeah (straight up, uh)
Ooh-ooh-ooh-ooh-ooh, tell somebody
You go tell somebody
Grandma told me
Get your money, black man (get your money)
Get your money, black man (get your money)
Get your money, black man (get your, black man)
Get your money, black man (get your, black man)
Black man
This is America (woo, ayy)
Don't catch you slippin' now (woo, woo, don't catch you slippin', now)
Don't catch you slippin' now (ayy, woah)
Look what I'm whippin' now (Slime!)
This is America (yeah, yeah)
Don't catch you slippin' now (woah, ayy)
Don't catch you slippin' now (ayy, woo)
Look what I'm whippin' now (ayy)
Look how I'm geekin' out (hey)
I'm so fitted (I'm so fitted, woo)
I'm on Gucci (I'm on Gucci)
I'm so pretty (yeah, yeah)
I'm gon' get it (ayy, I'm gon' get it)
Watch me move (blaow)
This a celly (ha)
That's a tool (yeah)
On my Kodak (woo, Black)
Ooh, know that (yeah, know that, hold on)
Get it (get it, get it)
Ooh, work it (21)
Hunnid bands, hunnid bands, hunnid bands (hunnid bands)
Contraband, contraband, contraband (contraband)
I got the plug on Oaxaca (woah)
They gonna find you like blocka (blaow)
Ooh-ooh-ooh-ooh-ooh, tell somebody
(America, I just checked my following list and)
You go tell somebody
(You mothafuckas owe me)
Grandma told me
Get your money, black man (black man)
Get your money, black man (black man)
Get your money, black man (black man)
Get your money, black man (black man)
Black man (one, two, three, get down)
Ooh-ooh-ooh-ooh-ooh, tell somebody
You go tell somebody
Grandma told me, "Get your money, " black man
Get your money, black man (black man)
Get your money, black man (black man)
Get your money, black man (black man)
Black man
You just a black man in this world
You just a barcode, ayy
You just a black man in this world
Drivin' expensive foreigns, ayy
You just a big dawg, yeah
I kenneled him in the backyard
No proper life to a dog
For a big dog

<img width=500 src="https://media.tenor.com/images/553a688449de0116ee1efb35a2b802a6/tenor.gif">

**Comment by FlamesX-128** [comment]
![emote](https://user-images.githubusercontent.com/78381898/107056937-7de85480-6798-11eb-9601-d28d6da197d7.png)
wtf
